# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  nodeTest:
    image: kademlia:latest # Make sure your Docker image has this name.
    init: true #test
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
      #        resources:
      #           limits:
      #              cpus: "0.1"
      #              memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - kademlia_network #STACK_kademlia_network
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - K=5
      - ALPHA=3
      - LISTEN_PORT=8888
      - SEND_PORT=8881
      - WAIT_FOR_RESPONSE_TIME=5

networks:
  kademlia_network:


